// Product category pages (bath + kitchen). Each entry renders with the product page template.
const bath = [
  {
    slug: 'showers', title: 'Showers', card: 'shower-8',
    hero: 'shower-1', lead: 'Low-maintenance, custom-fit showers designed around the way you live, installed fast by our own crews.',
    intro: { title: 'A Shower for <strong>Every Lifestyle</strong>', img: 'shower-2',
      text: '<p>Whether you want a sleek walk-in, a tub-to-shower conversion, or a safer low-threshold base, we build a shower that fits your space and your routine. Our solid-surface wall systems go up over a properly prepared substrate with no grout lines to scrub.</p>',
      bullets: ['Custom-measured bases and wall panels', 'Tub-to-shower conversions', 'Built-in seats, niches, and shelving', 'Slip-resistant textured floors'] },
    gallery: ['shower-3', 'shower-4', 'shower-5', 'shower-6', 'shower-7', 'shower-8', 'bath-1', 'bath-2', 'gallery-sh-1', 'gallery-sh-2', 'gallery-sh-3', 'gallery-sh-4', 'gallery-sh-5'],
    feature: { title: 'Stunning, <strong>Space-Saving Showers</strong>', img: 'bath-3',
      text: '<p>Small bathroom? A frameless glass door and a low-profile base can make the room feel twice as big. We help you pick the layout, trim, and fixtures that open up the space without sacrificing storage.</p>' },
  },
  {
    slug: 'bathtubs', title: 'Bathtubs', card: 'tub-8',
    hero: 'tub-1', lead: 'Replace a worn, dated tub with a durable, easy-clean bath and a matching wall surround — often in a single day.',
    intro: { title: 'A Bath Built for <strong>Relaxing</strong>', img: 'tub-2',
      text: '<p>From classic alcove tubs to deep soakers, our bathtubs are built to resist chips, stains, and fading. Pair one with a seamless wall system and you get a finished, spa-like look with almost no upkeep.</p>',
      bullets: ['Soaking and standard depths', 'Chip- and stain-resistant finishes', 'Shower-to-tub conversions', 'Matching wall surrounds and trim'] },
    gallery: ['tub-3', 'tub-4', 'tub-1', 'tub-6', 'tub-7', 'tub-8', 'bath-4', 'bath-5', 'gallery-tub-1', 'gallery-tub-2', 'gallery-tub-3', 'gallery-tub-4', 'gallery-tub-5', 'gallery-tub-6', 'gallery-tub-7', 'gallery-tub-8'],
    feature: { title: 'Family-Friendly <strong>Tub &amp; Shower Combos</strong>', img: 'bath-6',
      text: '<p>A tub-and-shower combo is still the most practical choice for many homes. We pair a comfortable tub with a full wall system, grab bars, and storage so the whole family can use it every day.</p>' },
  },
  {
    slug: 'walk-in-tubs', title: 'Walk-In Tubs', card: 'tub-5',
    hero: 'tub-4', lead: 'Bathe safely and comfortably with a low-entry, door-sealed walk-in tub and optional hydrotherapy.',
    intro: { title: 'Safety and Comfort, <strong>Every Day</strong>', img: 'senior-1',
      text: '<p>A walk-in tub lets you step in instead of climbing over a high wall. Built-in seating, a leak-proof door, and grab bars help you stay independent at home longer.</p>',
      bullets: ['Low step-in threshold', 'ADA-height built-in seat', 'Leak-tight door seal', 'Optional air and water jets', 'Handheld shower wand'] },
    gallery: ['tub-5', 'access-1', 'access-2', 'tub-6', 'bath-7', 'bath-8'],
    feature: { title: 'Therapeutic <strong>Hydrotherapy</strong>', img: 'tub-7',
      text: '<p>Optional air and water jet systems, heated backrests, and fast-drain valves turn your daily bath into a soothing routine that can ease sore muscles and joints.</p>' },
  },
  {
    slug: 'accessibility', title: 'Accessibility', card: 'access-3',
    hero: 'access-2', lead: 'Aging-in-place upgrades that make your bathroom safer for everyone, without looking clinical.',
    intro: { title: 'Safer Bathrooms, <strong>Beautiful Design</strong>', img: 'access-1',
      text: '<p>We design accessible bathrooms that look like any other upscale remodel. Barrier-free bases, fold-down seats, and well-placed grab bars reduce fall risk for seniors, people with limited mobility, and growing families.</p>',
      bullets: ['Low-threshold and roll-in shower bases', 'Fold-down and built-in seating', 'Decorative grab bars', 'Handheld showers and easy-reach controls'] },
    gallery: ['access-3', 'access-4', 'gallery-acc-1', 'gallery-acc-2', 'gallery-acc-3', 'gallery-acc-4', 'shower-3', 'bath-9', 'bath-10', 'bath-11'],
    feature: { title: 'Designed for <strong>Aging in Place</strong>', img: 'senior-2',
      text: '<p>Planning ahead? Our consultants walk through your daily routine and recommend the right mix of safety features so your bathroom keeps working for you for years to come.</p>' },
  },
  {
    slug: 'shower-enclosures', title: 'Shower Enclosures', card: 'shower-6',
    hero: 'shower-4', lead: 'Glass doors and enclosures that finish your shower and keep water where it belongs.',
    intro: { title: 'Quality Bath and <strong>Shower Enclosures</strong>', img: 'shower-5',
      text: '<p>The finishing details are what make a new bath or shower feel complete, and the enclosure is one of the most important. The right glass door or curtain rod frames your new wall pattern, keeps water where it belongs, and gives you the privacy you want, while making the whole bathroom feel brighter and more open. At Bulldog Kitchen &amp; Bath, we offer a full range of shower doors, tub enclosures, and curtain rods, and we measure every opening so your enclosure fits precisely and seals properly.</p>'
        + '<p>Choose clear glass to show off your walls and let light flow through the room, or pick rain, frosted, or corrugated glass when you want more privacy with a decorative touch. Etched V-groove patterns add a custom look to most doors. Depending on your layout, we can install sliding and bypass doors that save space on tubs and wide showers, or pivot and hinged doors for a clean, frameless-style walk-in. Every door and rod comes in four coordinating finishes — matte black, brushed nickel, oil-rubbed bronze, and chrome — and a protective glass coating helps water bead off so cleanup stays quick.</p>',
      bullets: ['Sliding, bypass, and pivot doors', 'Clear, rain, frosted, and corrugated glass', 'Optional V-groove etched patterns', 'Four door and rod finishes'] },
    gallery: ['gallery-enc-1', 'gallery-enc-2', 'gallery-enc-3', 'gallery-enc-4', 'gallery-enc-5', 'gallery-enc-6', 'gallery-enc-7', 'gallery-enc-8', 'shower-6', 'shower-7', 'shower-8', 'bath-12', 'bath-13', 'bath-14'],
    feature: { title: 'Light, Open, and <strong>Easy to Clean</strong>', img: 'bath-15',
      text: '<p>Clear glass lets light flow through the room and shows off your new wall pattern. A protective coating helps water bead off so spots and soap scum wipe away.</p>' },
  },
  {
    slug: 'accessories', title: 'Accessories', card: 'accessory-2',
    hero: 'bath-16', lead: 'The finishing touches that make your new bathroom more useful every day.',
    intro: { title: 'Storage and Style <strong>Built In</strong>', img: 'accessory-1',
      text: '<p>Add the details that make a bathroom work: corner shelves, recessed niches, soap dishes, towel bars, and coordinated faucets and shower heads.</p>',
      bullets: ['Corner caddies and shelves', 'Recessed niches', 'Towel bars and hooks', 'Shower heads, faucets, and valves', 'Grab bars in designer finishes'] },
    gallery: ['accessory-2', 'accessory-3', 'accessory-4', 'bath-17', 'bath-18', 'bath-19'],
    feature: { title: 'Fixtures in <strong>Four Finishes</strong>', img: 'bath-20',
      text: '<p>Coordinate every fixture in chrome, brushed nickel, matte black, or brushed gold for a polished, consistent look from the shower to the sink.</p>' },
  },
  {
    slug: 'colors-patterns', title: 'Colors &amp; Patterns', plainTitle: 'Colors & Patterns', card: 'texture-13',
    hero: 'bath-21', lead: 'Stone-look, tile-look, and solid finishes to match any style — from classic to modern.',
    intro: { title: 'Find <strong>Your Finish</strong>', img: 'texture-1',
      text: '<p>Our wall systems come in a wide range of marble, granite, travertine, and solid colors, with optional tile patterns like subway, hexagon, and herringbone. Bring samples home during your consultation.</p>',
      bullets: ['Marble, granite, and stone looks', 'Subway, hex, and herringbone patterns', 'Solid colors in matte or gloss', 'Accent trim and border options'] },
    swatches: true,
    feature: { title: 'See It <strong>Before You Buy</strong>', img: 'design-1',
      text: '<p>Not sure what will work? Our designers can show you a 3D rendering of your bathroom with your chosen colors and patterns before anything is ordered.</p>' },
  },
];

const kitchen = [
  {
    slug: 'cabinets', title: 'Cabinets', card: 'cabinets-1',
    hero: 'cabinets-2', lead: 'New, refaced, or refinished cabinets that bring order and style to the heart of your home.',
    intro: { title: 'Cabinets Built for <strong>Real Life</strong>', img: 'cabinets-3',
      text: '<p>Choose from shaker, flat-panel, and raised-panel doors in painted and wood finishes. We add the organizers you\'ll actually use — pull-outs, drawer dividers, and soft-close hardware throughout.</p>',
      bullets: ['Full replacement or cabinet refacing', 'Soft-close doors and drawers', 'Pull-out pantry and trash organizers', 'Painted, stained, and two-tone finishes'] },
    gallery: ['cabinets-4', 'cabinets-5', 'cabinets-6', 'kitchen-1', 'kitchen-2', 'kitchen-3'],
    feature: { title: 'Refacing: <strong>New Look, Less Disruption</strong>', img: 'kitchen-4',
      text: '<p>If your cabinet boxes are solid, refacing replaces doors, drawer fronts, and veneers for a brand-new look at a fraction of the time and cost of a full tear-out.</p>' },
  },
  {
    slug: 'countertops', title: 'Countertops', card: 'counter-1',
    hero: 'counter-2', lead: 'Quartz, granite, and solid-surface countertops fabricated and installed by our team.',
    intro: { title: 'Surfaces That <strong>Work Hard</strong>', img: 'counter-3',
      text: '<p>Your countertop takes daily abuse. We help you choose a surface that stands up to heat, stains, and scratches while matching your cabinets and floors.</p>',
      bullets: ['Quartz, granite, and solid surface', 'Undermount sink cutouts', 'Islands and breakfast bars', 'Edge profiles to suit your style'] },
    gallery: ['counter-4', 'counter-5', 'counter-6', 'kitchen-5', 'kitchen-6', 'kitchen-7'],
    feature: { title: 'Precise <strong>Templating &amp; Install</strong>', img: 'kitchen-8',
      text: '<p>We digitally template your existing layout for a tight, accurate fit, then install with minimal downtime so you can get back to cooking quickly.</p>' },
  },
  {
    slug: 'backsplash', title: 'Backsplash', card: 'backsplash-1',
    hero: 'backsplash-2', lead: 'A new backsplash is one of the fastest ways to transform your kitchen.',
    intro: { title: 'Add <strong>Personality</strong>', img: 'backsplash-3',
      text: '<p>Subway tile, mosaics, natural stone, or large-format panels — your backsplash protects your walls and sets the tone for the whole room.</p>',
      bullets: ['Ceramic, porcelain, and glass tile', 'Natural stone and mosaics', 'Grout-free panel options', 'Coordinated with your countertops'] },
    gallery: ['backsplash-4', 'backsplash-5', 'backsplash-6', 'kitchen-9', 'kitchen-10', 'kitchen-11'],
    feature: { title: 'Easy-Care <strong>Panel Backsplashes</strong>', img: 'kitchen-12',
      text: '<p>Prefer less cleaning? Our grout-free backsplash panels give you the look of tile with a smooth surface that wipes clean in seconds.</p>' },
  },
  {
    slug: 'sinks-faucets', title: 'Sinks &amp; Faucets', plainTitle: 'Sinks & Faucets', card: 'faucet-1',
    hero: 'faucet-2', lead: 'Upgrade the most-used spot in your kitchen with a sink and faucet that make cleanup easier.',
    intro: { title: 'Function Meets <strong>Finish</strong>', img: 'faucet-3',
      text: '<p>From deep single-bowl stainless sinks to farmhouse apron-front styles, we\'ll match your sink to your counters and cooking habits, then add a faucet that fits your workflow.</p>',
      bullets: ['Undermount, drop-in, and farmhouse sinks', 'Pull-down and touchless faucets', 'Filtered water and pot fillers', 'Garbage disposals and soap dispensers'] },
    gallery: ['faucet-4', 'faucet-5', 'faucet-6', 'kitchen-13', 'kitchen-14', 'kitchen-15'],
    feature: { title: 'Finishes That <strong>Tie It Together</strong>', img: 'kitchen-16',
      text: '<p>Match your faucet, cabinet pulls, and lighting in stainless, matte black, brushed gold, or polished chrome for a cohesive, designer look.</p>' },
  },
];

module.exports = { bath, kitchen };
