// Product category pages (bath + kitchen). Each entry renders with the product page template.
const bath = [
  {
    slug: 'showers', title: 'Showers', card: 'showers-card',
    hero: 'showers-header', lead: 'Low-maintenance, custom-fit showers designed around the way you live, installed fast by our own crews.',
    intro: { title: 'A Shower for <strong>Every Lifestyle</strong>', img: 'blog-tub-to-shower',
      text: '<p>Whether you want a sleek walk-in, a tub-to-shower conversion, or a safer low-threshold base, we build a cost-effective shower that fits your space and your routine. Our solid-surface wall systems go up over a properly prepared substrate with no grout lines to scrub.</p><p>Every base and wall panel is custom-measured for your space, and we can add built-in seats, niches, and shelving, plus a slip-resistant textured floor for safer footing. It all adds up to a convenient, affordable upgrade with long-term value.</p>' },
    gallery: ['showers-gallery-1', 'shower-enclosures-header', 'shower-enclosures-intro', 'shower-enclosures-card', 'showers-gallery-2', 'showers-card', 'showers-gallery-3', 'showers-gallery-4', 'showers-gallery-5', 'showers-gallery-6', 'showers-gallery-7', 'showers-gallery-8', 'showers-gallery-9'],
    feature: { title: 'Stunning, <strong>Space-Saving Showers</strong>', img: 'showers-feature',
      text: '<p>Small bathroom? A frameless glass door and a low-profile base can make the room feel twice as big. We help you pick the layout, trim, and fixtures that open up the space without sacrificing storage.</p>' },
  },
  {
    slug: 'bathtubs', title: 'Bathtubs', card: 'bathtubs-card',
    hero: 'bathtubs-header', lead: 'Replace a worn, dated tub with a durable, easy-clean bath and a matching wall surround, often in a single day.',
    intro: { title: 'A Bath Built for <strong>Relaxing</strong>', img: 'bathtubs-intro',
      text: '<p>From classic alcove tubs to deep soakers, our budget-friendly bathtubs are built to resist chips, stains, and fading. Pair one with a seamless wall system and you get a finished, spa-like look with almost no upkeep.</p><p>Choose a soaking or standard-depth tub, convert an existing shower back to a tub, and finish the space with a matching wall surround and trim.</p>' },
    gallery: ['bathtubs-gallery-1', 'walk-in-tubs-header', 'bathtubs-header', 'bathtubs-gallery-2', 'walk-in-tubs-feature', 'bathtubs-card', 'bathtubs-gallery-3', 'bathtubs-gallery-4', 'bathtubs-gallery-5', 'bathtubs-gallery-6', 'bathtubs-gallery-7', 'bathtubs-gallery-8', 'bathtubs-gallery-9', 'bathtubs-gallery-10', 'bathtubs-gallery-11', 'bathtubs-gallery-12'],
    feature: { title: 'Family-Friendly <strong>Tub &amp; Shower Combos</strong>', img: 'bathtubs-feature',
      text: '<p>A tub-and-shower combo is still the most practical choice for many homes. We pair a comfortable tub with a full wall system, grab bars, and storage so the whole family can use it every day, all at an affordable price.</p>' },
  },
  {
    slug: 'tub-to-shower-conversions', title: 'Tub-to-Shower Conversions', card: 'tub-to-shower-card',
    hero: 'tub-to-shower-header', lead: 'Swap a hard-to-step-over tub for a roomy, easy-entry walk-in shower, often in as little as one day.',
    intro: { title: 'From Tub to <strong>Walk-In Shower</strong>', img: 'tub-to-shower-intro',
      text: '<p>If you rarely take baths, that old tub is just a high wall you climb over every day. We remove it and install a custom-fit shower base and a solid-surface wall system in the same space, with no grout lines to scrub.</p><p>Choose a low-threshold or standard base and a glass door or curtain rod, then add a built-in seat, grab bars, shelves, and a handheld shower. Most conversions use the existing plumbing, which keeps the job fast and affordable.</p>' },
    gallery: ['tub-to-shower-gallery-1', 'tub-to-shower-card', 'tub-to-shower-gallery-2', 'tub-to-shower-gallery-3', 'tub-to-shower-gallery-4', 'tub-to-shower-intro'],
    feature: { title: 'Safer, <strong>Easier Showers</strong>', img: 'tub-to-shower-feature',
      text: '<p>A low step-in base, a slip-resistant floor, and well-placed grab bars make a converted shower safer for everyone, and a smart choice if you plan to stay in your home for years.</p>' },
  },
  {
    slug: 'walk-in-tubs', title: 'Walk-In Tubs', card: 'walk-in-tubs-card',
    hero: 'walk-in-tubs-header', lead: 'Bathe safely and comfortably with a low-entry, door-sealed walk-in tub and optional hydrotherapy.',
    intro: { title: 'Safety and Comfort, <strong>Every Day</strong>', img: 'promos-senior',
      text: '<p>A walk-in tub lets you step in instead of climbing over a high wall. Built-in seating, a leak-proof door, and grab bars help you stay independent at home longer.</p><p>Features include a low step-in threshold, an ADA-height seat, a leak-tight door seal, a handheld shower wand, and optional air and water jets.</p>' },
    gallery: ['walk-in-tubs-card', 'accessibility-intro', 'blog-aging-in-place', 'bathtubs-gallery-2', 'walk-in-tubs-gallery-1', 'walk-in-tubs-gallery-2'],
    feature: { title: 'Affordable <strong>Walk-In Tubs</strong>', img: 'walk-in-tubs-feature',
      text: '<p>Optional air and water jet systems, heated backrests, and fast-drain valves turn your daily bath into a soothing routine that can ease sore muscles and joints. With minimal disruption and no major remodeling, installation often takes as little as one day, making a walk-in tub a smart, affordable investment.</p>' },
  },
  {
    slug: 'accessibility', title: 'Accessibility', card: 'accessibility-card',
    hero: 'blog-aging-in-place', lead: 'Aging-in-place upgrades that make your bathroom safer for everyone, without looking clinical.',
    intro: { title: 'Safer Bathrooms, <strong>Beautiful Design</strong>', img: 'accessibility-intro',
      text: '<p>We design accessible bathrooms that look like any other upscale remodel. Barrier-free bases, fold-down seats, and well-placed grab bars reduce fall risk for seniors, people with limited mobility, and growing families.</p><p>We also add handheld showers and easy-reach controls, and every grab bar comes in a decorative finish that matches the rest of your fixtures.</p>' },
    gallery: ['accessibility-card', 'accessibility-gallery-1', 'accessibility-gallery-2', 'accessibility-gallery-3', 'accessibility-gallery-4', 'accessibility-gallery-5', 'showers-gallery-1', 'accessibility-gallery-6', 'accessibility-gallery-7', 'accessibility-gallery-8'],
    feature: { title: 'Designed for <strong>Aging in Place</strong>', img: 'accessibility-feature',
      text: '<p>Planning ahead? Our consultants walk through your daily routine and recommend the right mix of safety features so your bathroom keeps working for you for years to come.</p>' },
  },
  {
    slug: 'shower-enclosures', title: 'Shower Enclosures', card: 'shower-enclosures-card',
    hero: 'shower-enclosures-header', lead: 'Glass doors and enclosures that finish your shower and keep water where it belongs.',
    intro: { title: 'Quality Bath and <strong>Shower Enclosures</strong>', img: 'shower-enclosures-intro',
      text: '<p>The finishing details are what make a new bath or shower feel complete, and the enclosure is one of the most important. The right glass door or curtain rod frames your new wall pattern, keeps water where it belongs, and gives you the privacy you want, while making the whole bathroom feel brighter and more open. At Bulldog Kitchen &amp; Bath, we offer a full range of shower doors, tub enclosures, and curtain rods, and we measure every opening so your enclosure fits precisely and seals properly.</p>'
        + '<p>Choose clear glass to show off your walls and let light flow through the room, or pick rain, frosted, or corrugated glass when you want more privacy with a decorative touch. Etched V-groove patterns add a custom look to most doors. Depending on your layout, we can install sliding and bypass doors that save space on tubs and wide showers, or pivot and hinged doors for a clean, frameless-style walk-in. Every door and rod comes in four coordinating finishes (matte black, brushed nickel, oil-rubbed bronze, and chrome) and a protective glass coating helps water bead off so cleanup stays quick.</p>' },
    gallery: ['shower-enclosures-gallery-1', 'shower-enclosures-gallery-2', 'shower-enclosures-gallery-3', 'shower-enclosures-gallery-4', 'shower-enclosures-gallery-5', 'shower-enclosures-gallery-6', 'shower-enclosures-gallery-7', 'shower-enclosures-gallery-8', 'shower-enclosures-card', 'showers-gallery-2', 'showers-card', 'shower-enclosures-gallery-9', 'shower-enclosures-gallery-10', 'shower-enclosures-gallery-11'],
    feature: { title: 'Light, Open, and <strong>Easy to Clean</strong>', img: 'shower-enclosures-feature',
      text: '<p>Clear glass lets light flow through the room and shows off your new wall pattern. A protective coating helps water bead off so spots and soap scum wipe away.</p>' },
  },
  {
    slug: 'vanities', title: 'Bathroom Vanities', card: 'vanities-card',
    hero: 'vanities-header', lead: 'A new vanity, top, sink, and faucet that add storage and finish your bathroom, usually installed in a single day.',
    intro: { title: 'Storage and Style <strong>in One Piece</strong>', img: 'vanities-intro',
      text: '<p>Your vanity works harder than any other piece in the bathroom. We replace worn, cramped cabinets with sturdy vanities in single and double sizes, built to fit your space and your routine.</p><p>Pick a cabinet color and door style, a quartz, granite, or solid-surface top, and an undermount or vessel sink, then finish it with a faucet, mirror, and lighting that match.</p>' },
    gallery: ['vanities-card', 'vanities-gallery-1', 'vanities-gallery-2', 'vanities-gallery-3', 'vanities-gallery-4', 'vanities-gallery-5'],
    feature: { title: 'Single or <strong>Double Vanities</strong>', img: 'vanities-feature',
      text: '<p>Share a bathroom? A double vanity gives everyone their own sink and drawer space. Short on room? A compact single vanity with smart drawers keeps the counter clear.</p>' },
  },
  {
    slug: 'accessories', title: 'Accessories', card: 'bath-accessories-card',
    hero: 'bath-accessories-header', lead: 'The finishing touches that make your new bathroom more useful every day.',
    intro: { title: 'Storage and Style <strong>Built In</strong>', img: 'bath-accessories-intro',
      text: '<p>Add the details that make a bathroom work: corner shelves, recessed niches, soap dishes, towel bars, and coordinated faucets and shower heads.</p><p>Grab bars, hooks, and valves are available in designer finishes, so every piece matches and safety never looks clinical.</p>' },
    gallery: ['bath-accessories-card', 'accessory-3', 'accessory-4', 'bath-accessories-gallery-1', 'bath-accessories-gallery-2', 'faqs-header'],
    feature: { title: 'Fixtures in <strong>Four Finishes</strong>', img: 'design-spotlight-header',
      text: '<p>Coordinate every fixture in chrome, brushed nickel, matte black, or brushed gold for a polished, consistent look from the shower to the sink.</p>' },
  },
  {
    slug: 'colors-patterns', title: 'Colors &amp; Patterns', plainTitle: 'Colors & Patterns', card: 'colors-patterns-card',
    hero: 'financing-header', lead: 'Stone-look, tile-look, and solid finishes to match any style, from classic to modern.',
    intro: { title: 'Find <strong>Your Finish</strong>', img: 'colors-patterns-intro',
      text: '<p>Our wall systems come in a wide range of marble, granite, travertine, and solid colors, with optional tile patterns like subway, hexagon, and herringbone. Bring samples home during your consultation.</p><p>Solid colors come in matte or gloss, and accent trim and borders let you finish the look your way.</p>' },
    swatches: true,
    feature: { title: 'See It <strong>Before You Buy</strong>', img: 'colors-patterns-feature',
      text: '<p>Not sure what will work? Our designers can show you a 3D rendering of your bathroom with your chosen colors and patterns before anything is ordered.</p>' },
  },
];

const kitchen = [
  {
    slug: 'cabinets', title: 'Cabinets', card: 'kitchen-cabinets-card',
    hero: 'blog-cabinet-refacing', lead: 'New, refaced, or refinished cabinets that bring order and style to the heart of your home.',
    intro: { title: 'Cabinets Built for <strong>Real Life</strong>', img: 'kitchen-cabinets-intro',
      text: '<p>Choose from shaker, flat-panel, and raised-panel doors in painted and wood finishes. We add the organizers you\'ll actually use: pull-outs, drawer dividers, and soft-close hardware throughout.</p><p>We offer full replacement or cabinet refacing, with painted, stained, and two-tone finishes and pull-out pantry and trash organizers.</p>' },
    gallery: ['kitchen-cabinets-gallery-1', 'kitchen-cabinets-gallery-2', 'kitchen-cabinets-gallery-3', 'about-header', 'kitchen-cabinets-gallery-4', 'kitchen-cabinets-gallery-5'],
    feature: { title: 'Refacing: <strong>New Look, Less Disruption</strong>', img: 'kitchen-cabinets-feature',
      text: '<p>If your cabinet boxes are solid, refacing replaces doors, drawer fronts, and veneers for a brand-new look at a fraction of the time and cost of a full tear-out.</p>' },
  },
  {
    slug: 'countertops', title: 'Countertops', card: 'countertops-card',
    hero: 'countertops-header', lead: 'Quartz, granite, and solid-surface countertops fabricated and installed by our team.',
    intro: { title: 'Surfaces That <strong>Work Hard</strong>', img: 'countertops-intro',
      text: '<p>Your countertop takes daily abuse. We help you choose a surface that stands up to heat, stains, and scratches while matching your cabinets and floors.</p><p>Choose quartz, granite, or solid surface, with undermount sink cutouts, islands and breakfast bars, and an edge profile that suits your style.</p>' },
    gallery: ['countertops-gallery-1', 'countertops-gallery-2', 'countertops-gallery-3', 'countertops-gallery-4', 'countertops-gallery-5', 'countertops-gallery-6'],
    feature: { title: 'Precise <strong>Templating &amp; Install</strong>', img: 'countertops-feature',
      text: '<p>We digitally template your existing layout for a tight, accurate fit, then install with minimal downtime so you can get back to cooking quickly.</p>' },
  },
  {
    slug: 'backsplash', title: 'Backsplash', card: 'backsplash-card',
    hero: 'backsplash-header', lead: 'A new backsplash is one of the fastest ways to transform your kitchen.',
    intro: { title: 'Add <strong>Personality</strong>', img: 'backsplash-intro',
      text: '<p>Subway tile, mosaics, natural stone, or large-format panels: your backsplash protects your walls and sets the tone for the whole room.</p><p>Options include ceramic, porcelain, and glass tile, natural stone and mosaics, and grout-free panels, all coordinated with your countertops.</p>' },
    gallery: ['backsplash-gallery-1', 'backsplash-gallery-2', 'backsplash-gallery-3', 'backsplash-gallery-4', 'backsplash-gallery-5', 'backsplash-gallery-6'],
    feature: { title: 'Easy-Care <strong>Panel Backsplashes</strong>', img: 'backsplash-feature',
      text: '<p>Prefer less cleaning? Our grout-free backsplash panels give you the look of tile with a smooth surface that wipes clean in seconds.</p>' },
  },
  {
    slug: 'sinks-faucets', title: 'Sinks &amp; Faucets', plainTitle: 'Sinks & Faucets', card: 'sinks-faucets-card',
    hero: 'sinks-faucets-header', lead: 'Upgrade the most-used spot in your kitchen with a sink and faucet that make cleanup easier.',
    intro: { title: 'Function Meets <strong>Finish</strong>', img: 'sinks-faucets-intro',
      text: '<p>From deep single-bowl stainless sinks to farmhouse apron-front styles, we\'ll match your sink to your counters and cooking habits, then add a faucet that fits your workflow.</p><p>Choose an undermount, drop-in, or farmhouse sink and a pull-down or touchless faucet, then add filtered water, a pot filler, a garbage disposal, or a soap dispenser.</p>' },
    gallery: ['sinks-faucets-gallery-1', 'sinks-faucets-gallery-2', 'sinks-faucets-gallery-3', 'sinks-faucets-gallery-4', 'sinks-faucets-gallery-5', 'sinks-faucets-gallery-6'],
    feature: { title: 'Finishes That <strong>Tie It Together</strong>', img: 'sinks-faucets-feature',
      text: '<p>Match your faucet, cabinet pulls, and lighting in stainless, matte black, brushed gold, or polished chrome for a cohesive, designer look.</p>' },
  },
  {
    slug: 'organizers-accessories', title: 'Organizers &amp; Accessories', plainTitle: 'Organizers & Accessories', card: 'kitchen-organizers-card',
    hero: 'kitchen-organizers-header', lead: 'Pull-outs, drawer inserts, and racks that give everything in your kitchen a place, added in hours, not weeks.',
    intro: { title: 'A Place for <strong>Everything</strong>', img: 'kitchen-organizers-intro',
      text: '<p>Most kitchens don\'t need more cabinets, they need smarter ones. We fit your new or existing cabinets with organizers that make every inch easy to reach, from deep base cabinets to awkward corners.</p><p>Choose pull-out shelves, spice and tray pull-outs, trash and recycling pull-outs, cutlery and utensil inserts, lazy Susans for corners, and plate racks, plus pulls and knobs to finish the look.</p>' },
    gallery: ['kitchen-organizers-gallery-1', 'kitchen-organizers-gallery-2', 'kitchen-organizers-gallery-3', 'kitchen-organizers-gallery-4', 'kitchen-organizers-gallery-5', 'kitchen-organizers-gallery-6'],
    feature: { title: 'Pantry &amp; <strong>Cabinet Upgrades</strong>', img: 'kitchen-organizers-feature',
      text: '<p>Turn a cluttered pantry or upper cabinet into organized storage with roll-out shelves and racks sized to what you keep there, so nothing gets lost in the back.</p>' },
  },
];

module.exports = { bath, kitchen };
